### ISSUE TITLE
Request for earlier version functionality

### ISSUE THREAD

**Issue by ALFAIthildur** [RobRendell/OwlcatKingmakerModCraftMagicItems#1]
First of all, kudos on an excellent mod.
Having said that, I personally preferred the mod's earlier versions when it was simply Scribe Scrolls.  I've been enjoying that version of the mod until recently, when I started getting gui errors reported by the Unity Mod Manager (I click on the option icon to open up the mod, and nothing happens, other than the gui error being generated in the log). I'm not sure if it's due to updates of the game itself to 1.2 or updates/changes in Unity Mod Manager; would you have any insights on this? Or better yet, would you be willing to release the 'scrolls only' version of the mod updated to work with recent patches?

Thanks for your terrific contributions to a heck of a game!

**Comment by RobRendell** [comment]
Hi!  Thanks for the kind words.

The GUI error you're seeing is probably because the underlying method call used to get the characters in your party changed in Kingmaker 1.2.0.

I've just rebuilt the last version of Scribe Scroll (1.1.0) against the latest Kingmaker version - see how the attached file works for you.
[ScribeScroll.zip](https://github.com/RobRendell/OwlcatKingmakerModCraftMagicItems/files/2811811/ScribeScroll.zip)

**Comment by ALFAIthildur** [comment]
Thanks so much! Giving this a try today.

**Comment by ALFAIthildur** [comment]
Worked like a charm, thanks so much!

**Comment by RobRendell** [comment]
Good to hear!  I'll close this issue.

**Comment by ALFAIthildur** [comment]
Hi Rob. The game updating to 1.2.3 seems to have brought up the same gui error. Hopefully this doesn't need to be requested every time the game is patched; maybe this is something I can update myself if you can direct me to the proper bit of code, rather than having you update a Scrolls only version every time the game updates.
