### ISSUE TITLE
Scribe Scrolls only version

### ISSUE THREAD

**Issue by ALFAIthildur** [RobRendell/OwlcatKingmakerModCraftMagicItems#2]
Hi Rob. The game updating to 1.2.3 seems to have brought up the same gui error with the Scribe Scrolls only version of the mod. Hopefully this doesn't need to be requested every time the game is patched; maybe this is something I can update myself if you can direct me to the proper bit of code, rather than having you update Scrolls only version every time the game updates.

I'm guessing there probably wouldn't be a huge demand from the rest of the PFKM community for a regularly updated scrolls only version of the mod. I prefer it because it's has less impact on the overall balance of the campaign, and because I usually prefer an old school approach when obtaining a choice magical item was much more exciting vs. simply paying for tailor made gear (just a personal preference obviously; doesn't take away from a terrific mod at all for those who'd like the option of having crafting similar to PnP and at some point I may give it a try for a future playthrough).

**Comment by RobRendell** [comment]
Hi!  If you look in the Files section of the mod, ScribeScrolls version 1.1.0b should be available to download, which I built against Kingmaker 1.2.3.

https://www.nexusmods.com/pathfinderkingmaker/mods/54?tab=files

If you want to try to build the mod yourself, I made a branch from version 1.1.0 whose only change is to bump the version number: https://github.com/RobRendell/OwlcatKingmakerModCraftMagicItems/tree/1.1-scribe-scroll

If you clone that branch, and download Visual Studio Community edition, you should hopefully be able to build the mod yourself.  Note that you have to do the UMM patch of a new version of Kingmaker first, before building.

You also need to point the solution at your Kingmaker .dlls... if you happen to have Steam installed in the same place as me (C:\Program Files (x86)\Steam) it Should Just Work, but otherwise you'll need to adjust things.  For me, the simplest way to do that would be to just edit the paths inside the .csproj file before trying to open the project... just search for C:\Program Files (x86)\Steam and replace it with the correct path to your Kingmaker folder.

https://github.com/RobRendell/OwlcatKingmakerModCraftMagicItems/blob/1.1-scribe-scroll/ScribeScroll/ScribeScroll.csproj

Oh, also, if the paths in the AfterBuild.bat file match your computer's paths, doing a "rebuild" of the solution will automatically copy the mod files to the Kingmaker Mods folder, which is very convenient when doing development.

**Comment by ALFAIthildur** [comment]
That's tremendous, thanks so much!! I wasn't aware it would require Visual Studio to compile - I'll see how this goes for the next update - I was expecting things along the lines of Infinity Engine or Aurora engine modding.
Regardless, kudos again for not only making an excellent mod (even though I'm personally choosing to not use all of it) but the outstanding ongoing support and improvements you've made available.
